### ISSUE TITLE
logo design

### ISSUE THREAD

**Issue by reallinfo** [OmkarPathak/Django-Bookworm#2]
Hello @OmkarPathak 

I contribute to open source software in my spare time. I noticed that you don't have a logo. If you want, I can design a logo for this warehouse. I will wait for feedback. Thanks...

**Comment by OmkarPathak** [comment]
@reallinfo thats great. Sure I would love to have a logo. Open a PR when your are done 😄

**Comment by reallinfo** [comment]
Yeah, I designed a logo. Also, I can apply them if there's a color you want. What do you think about the logo?

![bw](https://user-images.githubusercontent.com/36298335/47309451-1a74a000-d63d-11e8-870f-51c46e6a018e.jpg)

**Comment by OmkarPathak** [comment]
@reallinfo also, can you design a new logo for this website: https://omkarpathak.in. This is my personal portfolio website and it would be really nice if you can design a logo for that too 😄

**Comment by reallinfo** [comment]
I think you want this :) How is these? Also, also i will design a logo for your website.

![bm3](https://user-images.githubusercontent.com/36298335/47365737-e1900600-d6e4-11e8-9d2e-a5944ab6daad.jpg)

**Comment by OmkarPathak** [comment]
Perfect! This is what I wanted :smile: 
Amazingly done. Thank You :smile: :rocket: 
![screenshot from 2018-10-23 19-50-37](https://user-images.githubusercontent.com/17998893/47367268-fd9fa180-d6fc-11e8-9eee-594f253479b0.png)

**Comment by reallinfo** [comment]
I sent a pr and readme updated.
Btw, Can you give your website a repository link?

**Comment by OmkarPathak** [comment]
Thanks. Here it is: https://github.com/OmkarPathak/omkarpathak.github.io

**Comment by OmkarPathak** [comment]
@reallinfo any updates?

**Comment by reallinfo** [comment]
https://github.com/OmkarPathak/omkarpathak.github.io/issues/6

Please look here. :) I'm closing this problem, please let us continue from there.
